Angular 13 upgrade
systelab/systelab-preferences pull request #57
Opened 2021-11-18 10:55 UTC by apenalver2

Hi all,

Upgrade the angular(to v13) and other dependencies to the last version.
#56 

![image](https://user-images.githubusercontent.com/34027110/142402182-effd4371-d18f-4918-86f6-976c1b1c70d1.png)
![image](https://user-images.githubusercontent.com/34027110/142402225-265edff8-3a42-410a-bd26-42f65e0a0064.png)

Any comment is welcome

Thank you

2021-11-18 11:56 UTC, apenalver2 commented
Can someone help me fix why when Travis is doing the build is crashing?

Thank you

2021-11-30 20:29 UTC, alfonsserra requested changes

2021-11-30 20:29 UTC, alfonsserra commented on package.json
> +  "version": "10.0.0",
Please do not change this one. Change the Library one to be published.

2021-11-30 20:30 UTC, alfonsserra commented on package.json
> +  "version": "10.0.0",
Please change this one: https://github.com/systelab/systelab-preferences/blob/angular-13-upgrade/projects/systelab-preferences/package.json

2021-12-13 13:17 UTC, alfonsserra approved these changes

2021-12-14 09:27 UTC, oGalceran1 approved these changes
Thanks

2022-10-18 14:21 UTC, olgapuig commented
This PR is closed without merging. The Angular update from 12 to 14 is being done at https://github.com/systelab/systelab-preferences/issues/56

2022-10-18 14:21 UTC, closed without merging