Update to Angular 16
systelab/systelab-preferences pull request #92
Opened 2023-10-11 14:31 UTC by fjaguado

2023-10-11 15:05 UTC, oGalceran1 approved these changes

2023-10-11 15:41 UTC, joaquimvila requested changes
I miss updating package.json under "projects/systelab-preferences".
Mind to set the range of accepted Angular versions between 16 and 17

2023-10-11 15:42 UTC, joaquimvila requested changes

2023-10-11 15:42 UTC, joaquimvila commented on package.json
> +    "protractor": "~7.0.0",
Can we get rid of protractor? If that's the case, I would take advantadge of this PR to do so.

2023-10-13 06:26 UTC, oGalceran1 approved these changes

2023-10-13 12:02 UTC, jserra91 approved these changes

2023-10-13 13:57 UTC, joaquimvila approved these changes

2023-10-13 14:02 UTC, merged